### ISSUE TITLE
On this day - not working

### ISSUE THREAD

**Issue by lkind** [mlava/wikipedia#2]
can only get the "featured content" to work - both "on this day" and "featured image" give "Error loading data from Wikipedia". Same issue with previous versions. Running default settings. Tried both un-encrypted and encrypted graph.

**Comment by mlava** [comment]
thanks @lkind 

I've created a new version that fixes this issue https://github.com/Roam-Research/roam-depot/pull/871

Wikimedia now requires an API token for the on this day, feat image.

Hopefully the RR guys can review and approve soon and it should work after that.

**Comment by mlava** [comment]
@lkind 
Confirming this update has now been accepted and is live in the Roam Depot.
Cheers!

**Comment by lkind** [comment]
Perfect !! works like a charm - thanks!!

/lars

*mvh/br*
*Lars Kindem*

Sent via Superhuman ( ***@***.*** )
